name: "Deploy Databricks Bundle"
description: "Deploy a Databricks Asset Bundle to a target environment"
inputs:
  target:
    description: "Deployment target (dev/uat/prod)"
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install Databricks CLI
      run: pip install databricks-cli databricks-sdk

    - name: Deploy Bundle
      run: databricks bundle deploy --target ${{ inputs.target }}
