name: "Azure OIDC Login"
description: "Authenticate to Azure using federated credentials"
inputs:
  environment:
    description: "Deployment environment (dev/uat/prod)"
    required: true
  client-id:
    description: "Azure Client ID"
    required: true
  tenant-id:
    description: "Azure Tenant ID"
    required: true
  subscription-id:
    description: "Azure Subscription ID"
    required: true

runs:
  using: "composite"
  steps:
    - name: Azure Login via OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}
        
    - name: Optional debug - show logged in account
      shell: bash
      run: az account show
