name: "Reusable Deploy Workflow"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout global templates
        uses: actions/checkout@v4
        with:
          repository: Himaan1502/databricks-ci-cd-templates
          ref: main

      - name: Use Deploy Action
        uses: ./github/actions/deploy
        with:
          env-file: env/${{ inputs.environment }}.txt
