name: "Databricks CI/CD"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      client-id:
        required: true
        type: string
      tenant-id:
        required: true
        type: string
      subscription-id:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Working Repo
        uses: actions/checkout@v4

      - name: Azure OIDC Login
        uses: ./actions/login
        with:
          environment: ${{ inputs.environment }}
          client-id: ${{ inputs.client-id }}
          tenant-id: ${{ inputs.tenant-id }}
          subscription-id: ${{ inputs.subscription-id }}

      - name: Deploy Bundle
        uses: ./actions/deploy
        with:
          target: ${{ inputs.environment }}
