name: "Databricks CI/CD"
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      client-id:
        required: true
      tenant-id:
        required: true
      subscription-id:
        required: true

permissions:
  id-token: write  # Required for OIDC
  contents: read   # Required to checkout code

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}  # GitHub Environment for protection rules
    steps:
      - name: Checkout Working Repo
        uses: actions/checkout@v4
        with:
          path: working-repo
          
      - name: Checkout Template Repo (for actions)
        uses: actions/checkout@v4
        with:
          repository: Himaan1502/databricks-ci-cd-templates
          path: template-repo
          ref: main
          
      - name: Azure OIDC Login
        uses: ./template-repo/actions/login
        with:
          environment: ${{ inputs.environment }}
          client-id: ${{ secrets.client-id }}
          tenant-id: ${{ secrets.tenant-id }}
          subscription-id: ${{ secrets.subscription-id }}
          
      - name: Deploy Bundle
        uses: ./template-repo/actions/deploy
        with:
          target: ${{ inputs.environment }}
        env:
          WORKING_REPO_PATH: ./working-repo
