name: Validate Databricks Bundle

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Checkout Global Templates
        uses: actions/checkout@v4
        with:
          repository: Himaan1502/databricks-ci-cd-templates
          ref: main
          path: ./.github/templates

      - name: Use Run Action for Validation
        uses: ./.github/actions/run
        with:
          command: "bundle validate --target ${{ inputs.environment }}"
          env-file: env/${{ inputs.environment }}.txt
